import styles from '@/styles/Home.module.css'
import { SignInButton, SignOutButton, SignedIn, SignedOut, useUser } from '@clerk/nextjs'
import Head from 'next/head'

export default function Home() {
  const { user } = useUser();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SignedIn>
          <div className={styles.container}>
            Hello, {user?.firstName || 'Known User'}!
          </div>
          <SignOutButton></SignOutButton>
        </SignedIn>
        <SignedOut>
          <div className={styles.container}>
            <SignInButton></SignInButton>
          </div>
          <div className={styles.container}>
            Hello, Stranger!
          </div>
        </SignedOut>
      </main>
    </>
  )
}
